apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-service-deployment
  labels:
    app: db-service
spec:
  template:
    metadata:
      name: db-service-pod
      labels:
        app: db-service
    spec:
      containers:
        - name: db-service-container
          image: nitendra18/db-service
  replicas: 6
  selector:
    matchLabels:
      app: db-service